# Generated by Django 5.1 on 2024-08-27 03:04

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="BookapptModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("username", models.CharField(max_length=10)),
                ("contactno", models.CharField(max_length=10)),
                ("name", models.CharField(max_length=10)),
                ("speciality", models.CharField(max_length=10)),
                ("schedule", models.CharField(max_length=10)),
                ("status", models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name="CustomerModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("userid", models.CharField(max_length=10)),
                ("speciality", models.CharField(max_length=10)),
                ("contactno", models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name="DoctorModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=10)),
                ("speciality", models.CharField(max_length=10)),
                ("schedule", models.CharField(max_length=10)),
            ],
        ),
    ]
