# Generated by Django 3.2 on 2021-05-08 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthcare_app', '0002_customermodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='customermodel',
            name='speciality',
            field=models.CharField(default='nil', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='doctormodel',
            name='speciality',
            field=models.CharField(default=10, max_length=10),
            preserve_default=False,
        ),
    ]
