# Generated by Django 3.2 on 2021-05-08 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthcare_app', '0004_bookapptmodel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookapptmodel',
            old_name='appt',
            new_name='name',
        ),
        migrations.AddField(
            model_name='bookapptmodel',
            name='schedule',
            field=models.CharField(default=0, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bookapptmodel',
            name='speciality',
            field=models.CharField(default=2, max_length=10),
            preserve_default=False,
        ),
    ]
