# Generated by Django 3.2 on 2021-05-09 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthcare_app', '0005_auto_20210508_1558'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookapptmodel',
            name='status',
            field=models.CharField(default=2, max_length=10),
            preserve_default=False,
        ),
    ]
