# Generated by Django 3.2 on 2021-05-09 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthcare_app', '0009_remove_bookapptmodel_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookapptmodel',
            name='status',
            field=models.CharField(default='PENDING', max_length=10),
            preserve_default=False,
        ),
    ]
